# docker-compose.yml
version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./results_shift:/app/results_shift
      - ./models:/app/models
    restart: unless-stopped